# Generated by Django 4.1 on 2022-08-21 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=300)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.BigIntegerField()),
                ('location', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime(2022, 8, 21, 22, 5, 6, 45191))),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
